const razones = [
  "Tu sonrisa ilumina mis días.",
  "Siempre sabes cómo hacerme reír.",
  "Tu voz me tranquiliza.",
  "Tienes un corazón lleno de amor.",
  "Me haces sentir especial cada día.",
  "Eres mi mejor amiga y mi amor.",
  "Tus abrazos me hacen sentir en casa.",
  "Contigo todo es mejor.",
  "Tu ternura me derrite.",
  "A tu lado todo tiene sentido.",
  "Eres mi sol en días nublados.",
  "Amo cómo me miras.",
  "Tu apoyo incondicional significa el mundo para mí.",
  "Haces que cada momento sea mágico.",
  "Eres perfecta tal y como eres.",
  "Tienes el alma más hermosa que conozco.",
  "Gracias a ti, creo en el amor verdadero.",
  "Tienes un encanto natural irresistible.",
  "Me inspiras a ser mejor cada día.",
  "Eres simplemente tú, y eso basta para amarte.",
  "Porque siempre estás ahí para mí.",
  "Porque me aceptas tal como soy.",
  "Tus detalles me enamoran cada día.",
  "Me haces reír incluso en mis peores días.",
  "Eres mi paz y mi refugio.",
  "Tu forma de ver la vida me motiva.",
  "Tu dulzura me derrite el corazón.",
  "Siempre sabes qué decir.",
  "Contigo aprendí a amar sin miedo.",
  "Eres mi alegría diaria.",
  "Tu presencia me hace sentir completo.",
  "Nuestro amor es mi tesoro más grande.",
  "Me haces sentir importante.",
  "Siempre me das fuerzas para seguir.",
  "Tienes una mirada que enamora.",
  "Eres el abrazo que calma todo.",
  "No hay nadie como tú.",
  "Tienes un alma preciosa.",
  "Tu compañía es mi lugar favorito.",
  "Eres la melodía más linda de mi vida.",
  "Nuestro amor es mi motor.",
  "Me haces creer en los milagros.",
  "Eres arte puro.",
  "Eres mi todo.",
  "Amo tus ocurrencias.",
  "Eres una bendición en mi vida.",
  "No hay día que no te piense.",
  "Mi corazón late por ti.",
  "Tu ternura es infinita.",
  "Gracias por existir.",
  "Eres lo mejor que me pasó.",
  "Tú haces de lo simple algo mágico.",
  "Adoro tu voz.",
  "Eres mi inspiración constante.",
  "A tu lado soy feliz.",
  "Me haces sentir amado.",
  "Eres la estrella que guía mi camino.",
  "Siempre me sorprendes.",
  "Tienes un brillo especial.",
  "Mi mundo gira en torno a ti.",
  "Tu esencia me enamora.",
  "Contigo me siento en casa.",
  "Amo cada momento contigo.",
  "Eres mi razón para sonreír.",
  "Nuestro amor es único.",
  "Tu piel es mi adicción.",
  "Tu manera de amar me conquistó.",
  "Tienes el corazón más lindo.",
  "Eres luz en mis días oscuros.",
  "Amo cómo cuidas de mí.",
  "Eres mi sueño hecho realidad.",
  "Tu felicidad es mi felicidad.",
  "Juntos todo es mejor.",
  "No me canso de mirarte.",
  "Cada día te amo más.",
  "Tu amor es mi fortuna.",
  "Eres magia pura.",
  "Gracias por tanto amor.",
  "Eres única.",
  "Tu inteligencia me encanta.",
  "Tu belleza interior me atrapa.",
  "Amo nuestras conversaciones.",
  "Amo compartir la vida contigo.",
  "Eres poesía viva.",
  "Tu energía me contagia.",
  "Eres mi sol en cada amanecer.",
  "Amo tu espontaneidad.",
  "Me completas.",
  "Tu dulzura me desarma.",
  "Nuestro amor es eterno.",
  "Eres mi inspiración.",
  "Todo contigo es amor.",
  "Tu voz es mi canción favorita.",
  "Eres más hermosa de lo que imaginas.",
  "Eres todo lo que siempre soñé.",
  "Amarte es lo más fácil del mundo.",
  "Amo lo fuerte que eres.",
  "Gracias por elegirme cada día.",
  "Me haces sentir vivo.",
  "Nuestro amor es real.",
  "Eres el mejor capítulo de mi vida.",
  "Te amo porque sí, sin razón específica, solo porque eres tú."
];

function mostrarRazon() {
  const razon = document.getElementById('razon');
  const indice = Math.floor(Math.random() * razones.length);
  razon.textContent = razones[indice];
}
